name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Runs ESlint
        run: npm run lint