name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run k6 load tests
        uses: k6io/action@v0.1
        with:
          filename: script.js
        
      - name: Runs ESlint
        run: npm run lint